#Usage: ansible-playbook -e Target=VM -e Name=name -e Password="password" change_password.yml
#Adhoc: ansible all -m user -a 'name=name password="password"'
#Safety password can be used using 'mkpasswd'
---
- hosts: "{{ Target }}"
  gather_facts: no
  tasks:
    - user: 
        name: "{{ Name }}" 
        password: "{{ Password | password_hash('sha512') }}"
